### ISSUE TITLE
Execute in Kaggle / Colab

### ISSUE THREAD

**Issue by claudiovaliense** [llm-merging/LLM-Merging#15]
I am trying to run the initial code on Kaggle, but I am getting the error "ModuleNotFoundError: No module named 'llm_merging'". Can you help me? I am executing the following commands:

!git clone https://github.com/llm-merging/LLM-Merging.git

!conda env create -f LLM-Merging/environment.yml --name llm-merging -y

!cd LLM-Merging && conda run -n llm-merging python llm_merging/setup.py install

!cd LLM-Merging && conda run -n llm-merging python llm_merging/main.py -m test_test

When executing "!conda run -n llm-merging pip list", "llm-merging 1.0" appears in the list, but the message "No module named 'llm_merging'" still appears.

**Comment by dptam** [comment]
I am guessing the PYTHONPATH might not be correct. It should include LLM-Merging at the end.
Can you try adding 
```
PYTHONPATH=`pwd`
```
before `python llm_merging/main.py -m test_test`. 

Can you also include the stack trace.

**Comment by claudiovaliense** [comment]
Thank you.
