### ISSUE TITLE
Can we use merge kit methods ?

### ISSUE THREAD

**Issue by ahmedamrelhefnawy** [llm-merging/LLM-Merging#16]
Can we use merge kit methods to build the model instead of building a new method from scratch when needed?

Knowing that we will reimplement it to be compatible with the Starter kit and be executed using the command:
`python llm_merging/main.py -m {merging_method}`

**Comment by borgr** [comment]
Better to ask in discord as it is not a starter kit question (and was asked there before :-) ), but yes you can use merge kit.
