### ISSUE TITLE
submission file size using the default piepline

### ISSUE THREAD

**Issue by himsR** [llm-merging/LLM-Merging#19]
Hello,

I followed the read me and created the llama_avg.tar to make sure I understand how the entire pipeline works including submission.
But the tar file is more than 200 Mbs and its because the output folder for llama_avg (/home/himanshu/nips/LLM-Merging/output/llama_avg/safetensor.pt) has a size of 160 MB. So my question is whether this should be deleted while submitting the tarred folder?

Thanks

**Comment by dptam** [comment]
Yes, the only file needed in the submission are the original files and your new `my_method.py` file.

**Comment by himsR** [comment]
thank you
