### ISSUE TITLE
README reference scores

### ISSUE THREAD

**Issue by sedrickkeh** [llm-merging/LLM-Merging#5]
Under "Test Method" in the README, it says 

> The datasets (CosmosQA and BoolQ) are mainly included for ensuring the merging method (with eval on those datasets) run in under the 1 hour time limit. Our results on llama_avg are {"cosmos_qa": {"accuracy": 0.234}, "xsum": {"rouge1": 0.123, "rouge2": 0.023, "rougeL": 0.093, "rougeLsum": 0.102}} , which run in about 25 minutes on our A6000.

However the [website](https://llm-merging.github.io/challenge) lists BoolQ and MAWPS as the test sets. Should this be updated?

**Comment by dptam** [comment]
Yes, thank you for pointing it out. We have the updated the website to reflect this.
