### ISSUE TITLE
Cannot run starter kit in Kaggle noteboook, normal?

### ISSUE THREAD

**Issue by NewJerseyStyle** [llm-merging/LLM-Merging#6]
# Outputs
## The following command:
```bash
python llm_merging/setup.py install 
python llm_merging/main.py -m LlamaAvg
```
## Error Message and Stack Trace (if applicable)
```
/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
Traceback (most recent call last):
  File "/kaggle/working/LLM-Merging/llm_merging/main.py", line 6, in <module>
    from llm_merging.evaluation import * 
ModuleNotFoundError: No module named 'llm_merging'
```
# Description
- I am trying to run the starter kit
- I expect to get a test result of LlamaAvg
- Instead it throw error
# System Info
## System Information
```
OS: Linux
Python Version: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
```

**Comment by NewJerseyStyle** [comment]
What is the system requirement for starterKit?

**Comment by dptam** [comment]
Did you try 
```
export PYTHONPATH=`pwd` 
```
The library requirements are `https://github.com/llm-merging/LLM-Merging/blob/main/environment.yml` and it was tested on CUDA 10.1

**Comment by NewJerseyStyle** [comment]
@dptam Thanks for reply, I did include
```bash
export PYTHONPATH=`pwd`
```

I guess its a problem with `conda` maybe the conda environment is not activated.
And I saw report of issue about running `conda` on Kaggle.

My last trial is using cell:
```
!conda env create -f environment.yml --name llm-merging
!source /opt/conda/bin/activate llm-merging 
!export PYTHONPATH=`pwd`
!export HF_AUTH_TOKEN=""
!/opt/conda/envs/llm-merging/bin/python llm_merging/setup.py install
!/opt/conda/envs/llm-merging/bin/python llm_merging/main.py -m LlamaAvg
```
Got same error

Can you verify the issue that starterkit cannot run on Kaggle?

**Comment by dptam** [comment]
I would need some time to try it on Kaggle and verify. 

Meanwhile, what happens with 
1)  `echo $PYTHONPATH`? 
2) Run `!/opt/conda/envs/llm-merging/bin/python` then 
```
import os
os.environ["PYTHONPATH"]
```

**Comment by NewJerseyStyle** [comment]
> I would need some time to try it on Kaggle and verify.
> 
> Meanwhile, what happens with
> 
> 1. `echo $PYTHONPATH`?
> 2. Run `!/opt/conda/envs/llm-merging/bin/python` then
> 
> ```
> import os
> os.environ["PYTHONPATH"]
> ```
Output of 1.
```
/kaggle/lib/kagglegym:/kaggle/lib
```
Output of 2.
```
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ModuleNotFoundError: No module named 'google.auth'
```

**Comment by dptam** [comment]
Thanks for running it. 

The `PYTHONPATH` variable should include `LLM-Merging` at the end.  

What location did you run 
```
export PYTHONPATH=`pwd`
```

**Comment by NewJerseyStyle** [comment]
So I end up not using export, did not find a way to make export work.

I defined the environment variable at the same line with the command, and things work
```bash
PYTHONPATH=`pwd` /opt/conda/envs/llm-merging/bin/python llm_merging/main.py -m llama_avg
```

**Comment by claudiovaliense** [comment]
@NewJerseyStyle Can you share all the commands that were necessary to get it running on Kaggle? I am having the same problem.

**Comment by NewJerseyStyle** [comment]
@claudiovaliense Same commands included in Starterkit README. Just try not to use `conda` and `export`

**Comment by claudiovaliense** [comment]
@NewJerseyStyle 
I am trying to run the initial code on Kaggle, but I am getting the error "ModuleNotFoundError: No module named 'llm_merging'". Can you help me? I am executing the following commands:

!git clone https://github.com/llm-merging/LLM-Merging.git

!conda env create -f LLM-Merging/environment.yml --name llm-merging -y

!cd LLM-Merging && conda run -n llm-merging python llm_merging/setup.py install

!cd LLM-Merging && conda run -n llm-merging python llm_merging/main.py -m test_test

When executing "!conda run -n llm-merging pip list", "llm-merging 1.0" appears in the list, but the message "No module named 'llm_merging'" still appears.

**Comment by NewJerseyStyle** [comment]
@claudiovaliense I am not familiar with conda and I have no idea how to solve your problem, I used following lines, good luck!

!git clone https://github.com/llm-merging/LLM-Merging.git

%cd LLM-Merging

!pip install -q evaluate peft rouge_score bitsandbytes

!PYTHONPATH=`pwd` python llm_merging/setup.py install

!HF_AUTH_TOKEN="<hf_token>" PYTHONPATH=`pwd` python llm_merging/main.py -m <method>

**Comment by claudiovaliense** [comment]
Thank you.
